[project]
name = "chaty"
plan = "free"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["*"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[analytics]
enabled = false

[db]
enabled = true
port = 54322
password = "postgres"

[storage]
enabled = true
buckets = ["avatars", "posts", "stories", "messages"]

[realtime]
enabled = true
